### ISSUE TITLE
手机浏览器，最上面的按钮，会被 那六个导航遮住，能不能把页面往下调一点

### ISSUE THREAD

**Issue by jjss520** [xingxichen/smsForwardClientWeb#1]
如图[http://tiebapic.baidu.com/forum/w%3D580/sign=94e56aa765a446237ecaa56aa8207246/18006bd162d9f2d3aeeb3432ecec8a136127cc6e.jpg?tbpicau=2022-08-21-05_e320b7e277efbd5c08299b723e535464](url)

**Comment by xingxichen** [comment]
双击小房子能隐藏菜单

**Comment by jjss520** [comment]
> 双击小房子能隐藏菜单

了解了
再问一下，这个服务端是不是只能在转发软件里启用，我在用群晖搭的，连接内网的棒子，提示错误

**Comment by xingxichen** [comment]
这个web工程只是个界面，理论上你部署在任何你能访问的地方都可以。你访问的设备要跟棒子有网络连接才能控制（棒子也要开启对应的功能）
